# Generated by Django 2.2.6 on 2019-11-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_entry_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='owner',
        ),
    ]
