# Generated by Django 2.2.6 on 2019-11-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0009_entry_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='owner',
        ),
    ]
