# Generated by Django 2.2.6 on 2019-11-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0010_remove_entry_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
    ]
